default: &default
  adapter: postgresql
  encoding: unicode
  username: deploy
  password: pointer
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: scraper_development
test:
  <<: *default
  database: scraper_test
production:
  <<: *default
  database: scraper_production
